-- Enable PostGIS for location features
create extension if not exists postgis;

-- 1. ENUMS and TYPES
create type user_role as enum ('admin', 'user');

-- 2. TABLES

-- PROFILES (Syncs with auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  avatar_url text,
  role user_role default 'user',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- LOCATIONS (The core entity)
create table public.locations (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  description text,
  state text,
  country text,
  population integer,
  
  -- Geographic Location (Long/Lat)
  -- Use ::geography(Point, 4326) for GPS coordinates
  coordinates geography(Point, 4326),
  lat float,
  lng float, 
  
  -- High-level Ratings (0.0 to 10.0)
  overall_score numeric(4,2),
  cost_of_living_score numeric(4,2),
  job_prospects_score numeric(4,2),
  education_score numeric(4,2),
  healthcare_score numeric(4,2),
  infrastructure_score numeric(4,2),
  safety_score numeric(4,2),
  culture_score numeric(4,2),

  -- Detailed Metrics (Stored as JSONB for flexibility)
  -- Structure: { "housing": 2300, "utilities": 150, "groceries": 400 ... }
  cost_breakdown jsonb, 
  
  -- Structure: { "unemployment": "3.2%", "avg_salary": 85000, "top_industries": [...] }
  job_stats jsonb,
  
  -- Structure: { "schools_count": 227, "universities_count": 5, "graduation_rate": "88%" }
  education_stats jsonb,
  
  -- Structure: { "hospitals_count": 12, "insurance_coverage": "82%" }
  healthcare_stats jsonb,
  
  -- Structure: { "commute_time_mins": 26, "public_transit_score": 5, "bike_score": 70 }
  transport_stats jsonb,
  
  images text[], -- Array of image URLs
  
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- REVIEWS
create table public.reviews (
  id bigint generated by default as identity primary key,
  location_id bigint references public.locations(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz default now()
);

-- FAVORITES (User saved locations)
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  location_id bigint references public.locations(id) on delete cascade,
  created_at timestamptz default now(),
  unique(user_id, location_id)
);

-- 3. INDEXES
-- Spatial index for fast "nearby" queries
create index locations_geo_idx on public.locations using gist (coordinates);
-- Performance indexes
create index reviews_location_idx on public.reviews(location_id);
create index favorites_user_idx on public.favorites(user_id);

-- 4. TRIGGERS & FUNCTIONS

-- Function to handle new user signup (auto-create profile)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the above function
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Function to update 'updated_at' column
create or replace function update_modified_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new; 
end;
$$ language plpgsql;

create trigger update_locations_modtime
    before update on public.locations
    for each row execute procedure update_modified_column();

create trigger update_profiles_modtime
    before update on public.profiles
    for each row execute procedure update_modified_column();

-- 5. ROW LEVEL SECURITY (RLS)
alter table public.profiles enable row level security;
alter table public.locations enable row level security;
alter table public.reviews enable row level security;
alter table public.favorites enable row level security;

-- Profiles: Public read, partial self-update
create policy "Public profiles are viewable by everyone"
  on public.profiles for select
  using ( true );

create policy "Users can update own profile"
  on public.profiles for update
  using ( auth.uid() = id );

-- Locations: Public read, Admin write
create policy "Locations are public"
  on public.locations for select
  using ( true );

-- (Assuming admin Logic is handled via App logic or stricter database role check. 
-- For now, we'll allow authenticated users to view. 
-- Real admin policies depend on how you set the 'role' in profiles)

-- Reviews: Public read, Authenticated create
create policy "Reviews are public"
  on public.reviews for select
  using ( true );

create policy "Authenticated users can create reviews"
  on public.reviews for insert
  with check ( auth.role() = 'authenticated' );

-- Favorites: Private to user
create policy "Users can view their own favorites"
  on public.favorites for select
  using ( auth.uid() = user_id );

create policy "Users can add favorites"
  on public.favorites for insert
  with check ( auth.uid() = user_id );

create policy "Users can remove favorites"
  on public.favorites for delete
  using ( auth.uid() = user_id );
